_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
RANDOM_SEED: 18
SUPPORT_SHOT: 1
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION_VALUE: 0.5
  NUM_CLASS: 64
  DATASET: SSv2-Small
  META_BATCH: true
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 1
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 40000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 20000
  BATCH_SIZE: 2
  BATCH_SIZE_PER_TASK: 8
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  SUPPORT_QUERY_DIFF: true

TEST:
  ENABLE: true
  DATASET: SSv2-Small
  SHOT: [1, 5]
  BATCH_SIZE: 2
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: data/ssv2/
  ANNO_DIR: config/ssv2_small/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 100
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 2000
  STEPS: [0, 4, 6, 8]
  LRS: [1, 0.1, 0.05, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.0002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true

ADAPTER:
  NAME: ViT_CLIP
  PRETRAINED: ViT-B/16
  WIDTH: 768
  PATCH_SIZE: 16
  LAYERS: 12
  HEADS: 12
  ADAPTER_SCALE: 0.25

INIT_METHOD: tcp://localhost:1111
NUM_GPUS: 2
CUDA_VISIBLE_DEVICES: 0, 1
OUTPUT_DIR: output/SSv2_Small